// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	context "context"

	scheme "github.com/kagent-dev/kagent/go/api/clientset/versioned/scheme"
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ScheduledRunsGetter has a method to return a ScheduledRunInterface.
// A group's client should implement this interface.
type ScheduledRunsGetter interface {
	ScheduledRuns(namespace string) ScheduledRunInterface
}

// ScheduledRunInterface has methods to work with ScheduledRun resources.
type ScheduledRunInterface interface {
	Create(ctx context.Context, scheduledRun *apiv1alpha3.ScheduledRun, opts v1.CreateOptions) (*apiv1alpha3.ScheduledRun, error)
	Update(ctx context.Context, scheduledRun *apiv1alpha3.ScheduledRun, opts v1.UpdateOptions) (*apiv1alpha3.ScheduledRun, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, scheduledRun *apiv1alpha3.ScheduledRun, opts v1.UpdateOptions) (*apiv1alpha3.ScheduledRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha3.ScheduledRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha3.ScheduledRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha3.ScheduledRun, err error)
	ScheduledRunExpansion
}

// scheduledRuns implements ScheduledRunInterface
type scheduledRuns struct {
	*gentype.ClientWithList[*apiv1alpha3.ScheduledRun, *apiv1alpha3.ScheduledRunList]
}

// newScheduledRuns returns a ScheduledRuns
func newScheduledRuns(c *ApiV1alpha3Client, namespace string) *scheduledRuns {
	return &scheduledRuns{
		gentype.NewClientWithList[*apiv1alpha3.ScheduledRun, *apiv1alpha3.ScheduledRunList](
			"scheduledruns",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha3.ScheduledRun { return &apiv1alpha3.ScheduledRun{} },
			func() *apiv1alpha3.ScheduledRunList { return &apiv1alpha3.ScheduledRunList{} },
		),
	}
}
