// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	apiv1alpha3 "github.com/kagent-dev/kagent/go/api/clientset/versioned/typed/api/v1alpha3"
	v1alpha3 "github.com/kagent-dev/kagent/go/api/v1alpha3"
	gentype "k8s.io/client-go/gentype"
)

// fakeScheduledRuns implements ScheduledRunInterface
type fakeScheduledRuns struct {
	*gentype.FakeClientWithList[*v1alpha3.ScheduledRun, *v1alpha3.ScheduledRunList]
	Fake *FakeApiV1alpha3
}

func newFakeScheduledRuns(fake *FakeApiV1alpha3, namespace string) apiv1alpha3.ScheduledRunInterface {
	return &fakeScheduledRuns{
		gentype.NewFakeClientWithList[*v1alpha3.ScheduledRun, *v1alpha3.ScheduledRunList](
			fake.Fake,
			namespace,
			v1alpha3.SchemeGroupVersion.WithResource("scheduledruns"),
			v1alpha3.SchemeGroupVersion.WithKind("ScheduledRun"),
			func() *v1alpha3.ScheduledRun { return &v1alpha3.ScheduledRun{} },
			func() *v1alpha3.ScheduledRunList { return &v1alpha3.ScheduledRunList{} },
			func(dst, src *v1alpha3.ScheduledRunList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha3.ScheduledRunList) []*v1alpha3.ScheduledRun {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha3.ScheduledRunList, items []*v1alpha3.ScheduledRun) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
