// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_runs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScheduledRunExecution = `-- name: CreateScheduledRunExecution :one
INSERT INTO scheduled_run_execution (
    id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid,
    start_time, deadline, trigger, prompt, phase, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'Creating', 'InProgress')
ON CONFLICT (id) DO NOTHING
RETURNING id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at
`

type CreateScheduledRunExecutionParams struct {
	ID                    string
	ScheduledRunNamespace string
	ScheduledRunName      string
	ScheduledRunUid       string
	StartTime             time.Time
	Deadline              time.Time
	Trigger               string
	Prompt                string
}

func (q *Queries) CreateScheduledRunExecution(ctx context.Context, arg CreateScheduledRunExecutionParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, createScheduledRunExecution,
		arg.ID,
		arg.ScheduledRunNamespace,
		arg.ScheduledRunName,
		arg.ScheduledRunUid,
		arg.StartTime,
		arg.Deadline,
		arg.Trigger,
		arg.Prompt,
	)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.ScheduledRunUid,
		&i.StartTime,
		&i.Deadline,
		&i.CompletionTime,
		&i.Trigger,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.Status,
		&i.StatusMessage,
		&i.Prompt,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduledRunExecution = `-- name: GetScheduledRunExecution :one
SELECT id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at FROM scheduled_run_execution WHERE id = $1
`

func (q *Queries) GetScheduledRunExecution(ctx context.Context, id string) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, getScheduledRunExecution, id)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.ScheduledRunUid,
		&i.StartTime,
		&i.Deadline,
		&i.CompletionTime,
		&i.Trigger,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.Status,
		&i.StatusMessage,
		&i.Prompt,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduledRunExecutionByAgentInstanceID = `-- name: GetScheduledRunExecutionByAgentInstanceID :one
SELECT id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at FROM scheduled_run_execution WHERE agent_instance_id = $1
`

func (q *Queries) GetScheduledRunExecutionByAgentInstanceID(ctx context.Context, agentInstanceID *uuid.UUID) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, getScheduledRunExecutionByAgentInstanceID, agentInstanceID)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.ScheduledRunUid,
		&i.StartTime,
		&i.Deadline,
		&i.CompletionTime,
		&i.Trigger,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.Status,
		&i.StatusMessage,
		&i.Prompt,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInProgressScheduledRunExecutions = `-- name: ListInProgressScheduledRunExecutions :many
SELECT id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at FROM scheduled_run_execution WHERE status = 'InProgress'
ORDER BY start_time, id
`

func (q *Queries) ListInProgressScheduledRunExecutions(ctx context.Context) ([]ScheduledRunExecution, error) {
	rows, err := q.db.Query(ctx, listInProgressScheduledRunExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRunExecution
	for rows.Next() {
		var i ScheduledRunExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledRunNamespace,
			&i.ScheduledRunName,
			&i.ScheduledRunUid,
			&i.StartTime,
			&i.Deadline,
			&i.CompletionTime,
			&i.Trigger,
			&i.AgentInstanceID,
			&i.TaskID,
			&i.Status,
			&i.StatusMessage,
			&i.Prompt,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRunExecutions = `-- name: ListScheduledRunExecutions :many
SELECT id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at FROM scheduled_run_execution
WHERE scheduled_run_namespace = $1
    AND scheduled_run_name = $2
    AND scheduled_run_uid = $3
    AND ($4::timestamptz IS NULL
         OR (start_time, id) < ($4::timestamptz, $5::text))
ORDER BY start_time DESC, id DESC
LIMIT $6
`

type ListScheduledRunExecutionsParams struct {
	ScheduledRunNamespace string
	ScheduledRunName      string
	ScheduledRunUid       string
	BeforeTime            *time.Time
	BeforeID              string
	PageLimit             int32
}

func (q *Queries) ListScheduledRunExecutions(ctx context.Context, arg ListScheduledRunExecutionsParams) ([]ScheduledRunExecution, error) {
	rows, err := q.db.Query(ctx, listScheduledRunExecutions,
		arg.ScheduledRunNamespace,
		arg.ScheduledRunName,
		arg.ScheduledRunUid,
		arg.BeforeTime,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRunExecution
	for rows.Next() {
		var i ScheduledRunExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledRunNamespace,
			&i.ScheduledRunName,
			&i.ScheduledRunUid,
			&i.StartTime,
			&i.Deadline,
			&i.CompletionTime,
			&i.Trigger,
			&i.AgentInstanceID,
			&i.TaskID,
			&i.Status,
			&i.StatusMessage,
			&i.Prompt,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledRunExecution = `-- name: UpdateScheduledRunExecution :execrows
UPDATE scheduled_run_execution SET
    agent_instance_id = $1,
    task_id = $2,
    phase = $3,
    status = $4,
    status_message = $5,
    completion_time = $6,
    updated_at = NOW()
WHERE id = $7
    AND status = 'InProgress'
    AND (agent_instance_id IS NULL OR agent_instance_id = $1)
    AND (task_id IS NULL OR task_id = $2)
    AND CASE phase WHEN 'Creating' THEN 0 WHEN 'Dispatching' THEN 1 WHEN 'Polling' THEN 2 ELSE 3 END
        <= CASE $3::text WHEN 'Creating' THEN 0 WHEN 'Dispatching' THEN 1 WHEN 'Polling' THEN 2 ELSE 3 END
`

type UpdateScheduledRunExecutionParams struct {
	AgentInstanceID *uuid.UUID
	TaskID          *string
	Phase           string
	Status          string
	StatusMessage   string
	CompletionTime  *time.Time
	ID              string
}

func (q *Queries) UpdateScheduledRunExecution(ctx context.Context, arg UpdateScheduledRunExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduledRunExecution,
		arg.AgentInstanceID,
		arg.TaskID,
		arg.Phase,
		arg.Status,
		arg.StatusMessage,
		arg.CompletionTime,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
