// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_runs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createScheduledRunBinding = `-- name: CreateScheduledRunBinding :one
INSERT INTO scheduled_run_binding (scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, bound_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (scheduled_run_uid) DO NOTHING
RETURNING scheduled_run_uid, scheduled_run_namespace, scheduled_run_name, bound_user_id
`

type CreateScheduledRunBindingParams struct {
	ScheduledRunNamespace string
	ScheduledRunName      string
	ScheduledRunUid       string
	BoundUserID           string
}

func (q *Queries) CreateScheduledRunBinding(ctx context.Context, arg CreateScheduledRunBindingParams) (ScheduledRunBinding, error) {
	row := q.db.QueryRow(ctx, createScheduledRunBinding,
		arg.ScheduledRunNamespace,
		arg.ScheduledRunName,
		arg.ScheduledRunUid,
		arg.BoundUserID,
	)
	var i ScheduledRunBinding
	err := row.Scan(
		&i.ScheduledRunUid,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.BoundUserID,
	)
	return i, err
}

const createScheduledRunExecution = `-- name: CreateScheduledRunExecution :one
INSERT INTO scheduled_run_execution (
    id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid,
    start_time, deadline, trigger, prompt, user_id, phase, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'Creating', 'InProgress')
ON CONFLICT (id) DO NOTHING
RETURNING id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, user_id, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at
`

type CreateScheduledRunExecutionParams struct {
	ID                    string
	ScheduledRunNamespace string
	ScheduledRunName      string
	ScheduledRunUid       string
	StartTime             time.Time
	Deadline              time.Time
	Trigger               string
	Prompt                string
	UserID                string
}

func (q *Queries) CreateScheduledRunExecution(ctx context.Context, arg CreateScheduledRunExecutionParams) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, createScheduledRunExecution,
		arg.ID,
		arg.ScheduledRunNamespace,
		arg.ScheduledRunName,
		arg.ScheduledRunUid,
		arg.StartTime,
		arg.Deadline,
		arg.Trigger,
		arg.Prompt,
		arg.UserID,
	)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.ScheduledRunUid,
		&i.UserID,
		&i.StartTime,
		&i.Deadline,
		&i.CompletionTime,
		&i.Trigger,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.Status,
		&i.StatusMessage,
		&i.Prompt,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduledRunBinding = `-- name: GetScheduledRunBinding :one
SELECT scheduled_run_uid, scheduled_run_namespace, scheduled_run_name, bound_user_id FROM scheduled_run_binding
WHERE scheduled_run_namespace = $1 AND scheduled_run_name = $2 AND scheduled_run_uid = $3
`

type GetScheduledRunBindingParams struct {
	ScheduledRunNamespace string
	ScheduledRunName      string
	ScheduledRunUid       string
}

func (q *Queries) GetScheduledRunBinding(ctx context.Context, arg GetScheduledRunBindingParams) (ScheduledRunBinding, error) {
	row := q.db.QueryRow(ctx, getScheduledRunBinding, arg.ScheduledRunNamespace, arg.ScheduledRunName, arg.ScheduledRunUid)
	var i ScheduledRunBinding
	err := row.Scan(
		&i.ScheduledRunUid,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.BoundUserID,
	)
	return i, err
}

const getScheduledRunExecution = `-- name: GetScheduledRunExecution :one
SELECT id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, user_id, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at FROM scheduled_run_execution WHERE id = $1
`

func (q *Queries) GetScheduledRunExecution(ctx context.Context, id string) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, getScheduledRunExecution, id)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.ScheduledRunUid,
		&i.UserID,
		&i.StartTime,
		&i.Deadline,
		&i.CompletionTime,
		&i.Trigger,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.Status,
		&i.StatusMessage,
		&i.Prompt,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduledRunExecutionByAgentInstanceID = `-- name: GetScheduledRunExecutionByAgentInstanceID :one
SELECT e.id, e.scheduled_run_namespace, e.scheduled_run_name, e.scheduled_run_uid, e.user_id, e.start_time, e.deadline, e.completion_time, e.trigger, e.agent_instance_id, e.task_id, e.status, e.status_message, e.prompt, e.phase, e.created_at, e.updated_at FROM scheduled_run_execution e
WHERE e.agent_instance_id = $1
    OR (e.agent_instance_id IS NULL AND EXISTS (
        SELECT 1 FROM agent_instance i WHERE i.id = $1 AND e.id = i.request_id
            AND e.user_id = i.user_id
    ))
`

func (q *Queries) GetScheduledRunExecutionByAgentInstanceID(ctx context.Context, agentInstanceID *uuid.UUID) (ScheduledRunExecution, error) {
	row := q.db.QueryRow(ctx, getScheduledRunExecutionByAgentInstanceID, agentInstanceID)
	var i ScheduledRunExecution
	err := row.Scan(
		&i.ID,
		&i.ScheduledRunNamespace,
		&i.ScheduledRunName,
		&i.ScheduledRunUid,
		&i.UserID,
		&i.StartTime,
		&i.Deadline,
		&i.CompletionTime,
		&i.Trigger,
		&i.AgentInstanceID,
		&i.TaskID,
		&i.Status,
		&i.StatusMessage,
		&i.Prompt,
		&i.Phase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInProgressScheduledRunExecutions = `-- name: ListInProgressScheduledRunExecutions :many
SELECT id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, user_id, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at FROM scheduled_run_execution WHERE status = 'InProgress'
ORDER BY start_time, id
`

func (q *Queries) ListInProgressScheduledRunExecutions(ctx context.Context) ([]ScheduledRunExecution, error) {
	rows, err := q.db.Query(ctx, listInProgressScheduledRunExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRunExecution
	for rows.Next() {
		var i ScheduledRunExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledRunNamespace,
			&i.ScheduledRunName,
			&i.ScheduledRunUid,
			&i.UserID,
			&i.StartTime,
			&i.Deadline,
			&i.CompletionTime,
			&i.Trigger,
			&i.AgentInstanceID,
			&i.TaskID,
			&i.Status,
			&i.StatusMessage,
			&i.Prompt,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledRunExecutions = `-- name: ListScheduledRunExecutions :many
SELECT id, scheduled_run_namespace, scheduled_run_name, scheduled_run_uid, user_id, start_time, deadline, completion_time, trigger, agent_instance_id, task_id, status, status_message, prompt, phase, created_at, updated_at FROM scheduled_run_execution
WHERE scheduled_run_namespace = $1
    AND scheduled_run_name = $2
    AND scheduled_run_uid = $3
    AND ($4::timestamptz IS NULL
         OR (start_time, id) < ($4::timestamptz, $5::text))
ORDER BY start_time DESC, id DESC
LIMIT $6
`

type ListScheduledRunExecutionsParams struct {
	ScheduledRunNamespace string
	ScheduledRunName      string
	ScheduledRunUid       string
	BeforeTime            *time.Time
	BeforeID              string
	PageLimit             int32
}

func (q *Queries) ListScheduledRunExecutions(ctx context.Context, arg ListScheduledRunExecutionsParams) ([]ScheduledRunExecution, error) {
	rows, err := q.db.Query(ctx, listScheduledRunExecutions,
		arg.ScheduledRunNamespace,
		arg.ScheduledRunName,
		arg.ScheduledRunUid,
		arg.BeforeTime,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledRunExecution
	for rows.Next() {
		var i ScheduledRunExecution
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledRunNamespace,
			&i.ScheduledRunName,
			&i.ScheduledRunUid,
			&i.UserID,
			&i.StartTime,
			&i.Deadline,
			&i.CompletionTime,
			&i.Trigger,
			&i.AgentInstanceID,
			&i.TaskID,
			&i.Status,
			&i.StatusMessage,
			&i.Prompt,
			&i.Phase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduledRunExecution = `-- name: UpdateScheduledRunExecution :execrows
UPDATE scheduled_run_execution SET
    agent_instance_id = $1,
    task_id = $2,
    phase = $3,
    status = $4,
    status_message = $5,
    completion_time = $6,
    updated_at = NOW()
WHERE id = $7
    AND user_id = $8
    AND status = 'InProgress'
    AND (agent_instance_id IS NULL OR agent_instance_id = $1)
    AND (task_id IS NULL OR task_id = $2)
    AND CASE phase WHEN 'Creating' THEN 0 WHEN 'Dispatching' THEN 1 WHEN 'Polling' THEN 2 ELSE 3 END
        <= CASE $3::text WHEN 'Creating' THEN 0 WHEN 'Dispatching' THEN 1 WHEN 'Polling' THEN 2 ELSE 3 END
`

type UpdateScheduledRunExecutionParams struct {
	AgentInstanceID *uuid.UUID
	TaskID          *string
	Phase           string
	Status          string
	StatusMessage   string
	CompletionTime  *time.Time
	ID              string
	UserID          string
}

func (q *Queries) UpdateScheduledRunExecution(ctx context.Context, arg UpdateScheduledRunExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduledRunExecution,
		arg.AgentInstanceID,
		arg.TaskID,
		arg.Phase,
		arg.Status,
		arg.StatusMessage,
		arg.CompletionTime,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
